apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        persistentVolumeClaim:
          claimName: dir
      - name: credenciais-instancia-cloudsql
        secret:
          secretName: credenciais-instancia-cloudsql
      containers:
      - name: php
        image: gcr.io/poder360-dev/wordpress:fpm
        env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_NAME
          value: poder360
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define( 'FS_METHOD', 'direct' );
            define( 'DISABLE_WP_CRON', true );
            define( 'DISALLOW_FILE_MODS', true );
        # [START cloudsql_secrets]
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: credenciais-db-cloudsql
              key: username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credenciais-db-cloudsql
              key: password
        # [END cloudsql_secrets]
        volumeMounts:
        - name: dir
          mountPath: /var/www/html
      # Change <INSTANCE_CONNECTION_NAME> here to include your GCP
      # project, the region of your Cloud SQL instance and the name
      # of your Cloud SQL instance. The format is
      # $PROJECT:$REGION:$INSTANCE
      # [START proxy_container]
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                "-instances=poder360-dev:southamerica-east1:database360=tcp:3306",
                "-credential_file=/secrets/cloudsql/credentials.json"]
        # [START cloudsql_security_context]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        # [END cloudsql_security_context]
        volumeMounts:
          - name: credenciais-instancia-cloudsql
            mountPath: /secrets/cloudsql
            readOnly: true
       # [END proxy_container]
