apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    tier: backend
spec:
  selector:
    app: memcached
    tier: backend
  ports:
    - port: 11211
      protocol: TCP
    - port: 11211
      protocol: UDP
