apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-shares
spec:
  schedule: "0 *   * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-shares
            image: appropriate/curl
            args:
            - http://www.poder360.com.br/_elav_update_seven
          restartPolicy: OnFailure

