apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-eleicoes
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-eleicoes
            image: appropriate/curl
            args:
            - http://www.poder360.com.br/wp-content/themes/poder360/cron/eleicoes.php
          restartPolicy: OnFailure
