apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-elasticsearch
spec:
  schedule: "59 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-elasticsearch
            image: appropriate/curl
            args:
            - http://www.poder360.com.br/alertas/update_post_index/
          restartPolicy: OnFailure
